using Gtk;

public sealed record CameraWindow(
    ApplicationWindow Window,
    Picture Picture,
    Label Hud,
    ComboBoxText IsoBox,
    ComboBoxText ShutterBox,
    CheckButton AutoToggle,
    Scale ZoomScale,
    Scale PanXScale,
    Scale PanYScale,
    Button CaptureButton,
    Button SettingsButton,
    Button GalleryButton,
    ToggleButton ModeMenuToggle,
    ToggleButton ModePhotoToggle,
    ToggleButton ModeVideoToggle,
    ToggleButton ModeTimelapseToggle,
    Revealer ModeRevealer,
    Stack ModeStack,
    ComboBoxText VideoFpsCombo,
    SpinButton VideoShutterAngleSpin,
    Button VideoRecordButton,
    Label VideoStatusLabel,
    SpinButton TimelapseIntervalSpin,
    SpinButton TimelapseFrameCountSpin,
    Button TimelapseStartButton,
    Label TimelapseStatusLabel,
    Stack PageStack,
    Widget LivePage,
    CameraSettingsView SettingsView,
    Widget GalleryPage,
    GalleryView GalleryView
);
